.\" Manpage for opgpcard.
.\" Contact juga@riseup.net to correct errors or typos.
.TH man 8 "18 May 2018" "1.0" "opgpcard man page"
.SH NAME
opgpcard \- OpenPGP printable card
.SH SYNOPSIS
opgpcard [-h] [-d] [-o OUTPUTDIR] [-v] [-f FIRSTNAME] [-l LASTNAME]
         [-p FINGERPRINT] [-s] [-m MAIL]
.SH DESCRIPTION
Create a VCard, a QR code and/or a printable business cards including OpenPGP
key and fingerprint.
.SH OPTIONS
The options which apply to the opgpcard command are:

-h, --help
    Show help message and exit.

-d, --debug
    Show debug messages.

-f FIRSTNAME, --firstname FIRSTNAME

-l LASTNAME, --lastname LASTNAME

-p FINGERPRINT, --fingerprint FINGERPRINT

-s, --localsign

-m MAIL, --mail MAIL

-o OUTPUTDIR, --outputdir OUTPUTDIR

-v, --version
    Show version.
.SH AUTHOR
juga (juga@riseup.net)
