sudo: required
dist: bionic
arch:
     - amd64
     - ppc64le
language: python
python:
  - '3.6'
  - "3.7"
  - "3.8-dev"
#   - "nightly"
#   - "pypy3.5"
install: pip install tox-travis
script:
  - tox
  # This is not in included in the tox envlist, in order to don't need Internet
  # when running tox
  # - tox -e doclinks
  - tox -e clean

before_install:
  - gpg --version
  - sudo apt update && sudo apt install -y libgpgme-dev swig

# This is not installed before
# addons:
#   apt:
#     packages:
#       - libgpgme-dev
